/**
 * Windows service installation for HAPI daemon
 *
 * Uses schtasks to create a scheduled task that runs the daemon at user login.
 * This is the Windows equivalent of macOS LaunchDaemons.
 */

import { writeFileSync, existsSync, chmodSync } from 'fs';
import { execSync } from 'child_process';
import { join } from 'path';
import os from 'os';
import { logger } from '@/ui/logger';

const TASK_NAME = 'HAPI CLI Daemon';
const TASK_DESC = 'HAPI CLI background service for remote session management';

export async function install(): Promise<void> {
    const isWindows = process.platform === 'win32';
    if (!isWindows) {
        throw new Error('This function is only for Windows');
    }

    try {
        // Check if already installed
        try {
            execSync(`schtasks /Query /TN "${TASK_NAME}"`, { stdio: 'pipe' });
            logger.info('Daemon task already exists. Removing first...');
            execSync(`schtasks /Delete /TN "${TASK_NAME}" /F`, { stdio: 'inherit' });
        } catch {
            // Task doesn't exist, that's fine
        }

        // Get the path to bun executable and script
        const bunPath = process.argv[0];
        const scriptPath = process.argv[1];

        // Create a startup batch file
        const batchFileName = 'hapi-daemon-start.bat';
        const batchPath = join(os.homedir(), '.hapi', batchFileName);

        const batchContent = `@echo off
REM HAPI CLI Daemon Startup Script
REM Generated by hapi daemon install

set HAPI_DAEMON_MODE=true
"${bunPath}" "${scriptPath}" daemon start-sync
`;

        writeFileSync(batchPath, batchContent);
        chmodSync(batchPath, 0o755);
        logger.debug(`Created batch file at ${batchPath}`);

        // Create the scheduled task
        // Run on user login, with highest privileges, and allow manual start
        const xmlContent = `<?xml version="1.0" encoding="UTF-8"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>${TASK_DESC}</Description>
    <URI>\\${TASK_NAME}</URI>
  </RegistrationInfo>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowStartOnDemand>true>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeOnlyIfNetworkAvailable>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>cmd</Command>
      <Arguments>/c "${batchPath}"</Arguments>
      <WorkingDirectory>${os.tmpdir()}</WorkingDirectory>
    </Exec>
  </Actions>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>${os.userInfo().username}</UserId>
    </LogonTrigger>
  </Triggers>
</Task>
`;

        const xmlPath = join(os.homedir(), '.hapi', 'hapi-daemon-task.xml');
        writeFileSync(xmlPath, xmlContent);

        execSync(`schtasks /Create /XML "${xmlPath}" /TN "${TASK_NAME}" /F`, { stdio: 'inherit' });

        // Clean up temp XML file
        try {
            execSync(`del "${xmlPath}"`, { stdio: 'pipe' });
        } catch {
            // Ignore cleanup errors
        }

        logger.info('Daemon installed successfully for Windows');
        logger.info(`Task "${TASK_NAME}" will start at user login`);
        logger.info('Logs are stored in ~/.hapi/');

    } catch (error) {
        logger.debug('Failed to install daemon:', error);
        throw error;
    }
}

export async function uninstall(): Promise<void> {
    const isWindows = process.platform === 'win32';
    if (!isWindows) {
        throw new Error('This function is only for Windows');
    }

    try {
        // Try to delete the task
        execSync(`schtasks /Delete /TN "${TASK_NAME}" /F`, { stdio: 'inherit' });
        logger.info('Daemon uninstalled successfully');
    } catch (error) {
        // Task might not exist, that's fine
        if ((error as Error).message.includes('The system cannot find the file')) {
            logger.info('Daemon was not installed');
        } else {
            throw error;
        }
    }

    // Clean up batch file
    const batchPath = join(os.homedir(), '.hapi', 'hapi-daemon-start.bat');
    if (existsSync(batchPath)) {
        try {
            execSync(`del "${batchPath}"`, { stdio: 'pipe' });
        } catch {
            // Ignore cleanup errors
        }
    }
}
